version: "3.8"

services:
  mssql:
    container_name: springboot-db-test
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Docker123!@
    ports:
      - "1433:1433"
    networks:
      - springboot-mysql-net

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mssql
    environment:
      spring.datasource.url: jdbc:sqlserver://springboot-db-test:1433;databaseName=employees;encrypt=true;trustServerCertificate=true;
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net: