apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-db-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-db-test
  template:
    metadata:
      labels:
        app: springboot-db-test
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: "Docker123!@"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-db-test-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer