apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-restful-webservices
  template:
    metadata:
      labels:
        app: springboot-restful-webservices
    spec:
      containers:
        - name: springboot-restful-webservices
          image: badertawafsheh/springboot-docrized:latest
          ports:
            - containerPort: 8080
          env:
            - name: spring.datasource.url
              value: jdbc:sqlserver://springboot-db-test-service:1433;databaseName=master;encrypt=true;trustServerCertificate=true;
          readinessProbe:   
            tcpSocket:
              port: 1433


---
apiVersion: v1
kind: Service
metadata:
  name: springboot-restful-webservices
spec:
  selector:
    app: springboot-restful-webservices
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080